version: '3'

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  mongo-express:
    container_name: mongo-express
    hostname: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8888:8081"

  minio:
    image: minio/minio
    volumes:
      - minio_storage:/data
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  minio_create_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set dev_minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc rm -r --force dev_minio/${MINIO_DEFAULT_BUCKET};
      /usr/bin/mc mb dev_minio/${MINIO_DEFAULT_BUCKET};
      /usr/bin/mc policy set public dev_minio/${MINIO_DEFAULT_BUCKET};
      exit 0;
      "

volumes:
  mongo:
  minio_storage:

